#Configuração do Controller e das View
controllers:
  invokables:
    Application\Controller\Index: Application\Controller\IndexController
view_manager:
  display_not_found_reason: true
  display_exceptions: true
  doctype: HTML5
  not_found_template: error/404
  exception_template: error/index
  template_map:


#Configuração do Doctrine em relação ao Módulo
doctrine:
  driver:
      Application_driver:
        class: Doctrine\ORM\Mapping\Driver\AnnotationDriver
        cache: array
        paths:
        - ./module/Application/src/Application/Entity
      orm_default:
        drivers:
          Application\Entity: Application_driver

#Configuração das Fixtures do Módulo
data-fixture:
  Application_fixture: ./module/Application/src/Application/Fixture