controllers:
  invokables:
    Application\Controller\Index: Application\Controller\IndexController
view_manager:
  display_not_found_reason: true
  display_exceptions: true
  doctype: HTML5
  not_found_template: error/404
  exception_template: error/index
  template_map:
doctrine:
  driver:
    _driver:
      class: Doctrine\ORM\Mapping\Driver\AnnotationDriver
      cache: array
      paths:
      - /opt/YamlConv/../src/Entity
    orm_default:
      drivers:
        \Entity: _driver
data-fixture:
  _fixture: /opt/YamlConv/../src//Fixture