router:
  routes:
    home:
      type: Zend\Mvc\Router\Http\Literal
      options:
        route: /
        defaults:
          controller: Application\Controller\Index
          action: index
    application:
      type: Literal
      options:
        route: /index
        defaults:
          __NAMESPACE__: Application\Controller
          controller: Index
          action: load
      may_terminate: true
      child_routes:
        default:
          type: Segment
          options:
            route: /[:controller[/:action]]
            constraints:
              controller: '[a-zA-Z][a-zA-Z0-9_-]*'
              action: '[a-zA-Z][a-zA-Z0-9_-]*'
            defaults: []
service_manager:
  factories:
    translator: Zend\I18n\Translator\TranslatorServiceFactory
translator:
  locale: pt_BR
  translation_file_patterns:
        - type: gettext
          base_dir:  /../language
          pattern: '%s.mo'
controllers:
  invokables:
    Application\Controller\Index: Application\Controller\IndexController
view_manager:
  display_not_found_reason: true
  display_exceptions: true
  doctype: HTML5
  not_found_template: error/404
  exception_template: error/index
