service_manager:
  factories:
    translator: Zend\I18n\Translator\TranslatorServiceFactory
translator:
  locale: pt_BR
  translation_file_patterns:
        - type: gettext
          base_dir:  /home/diego/Downloads/simpleddns/module/Application/language
          pattern: '%s.mo'
controllers:
  invokables:
    Application\Controller\Index: Application\Controller\IndexController
view_manager:
  display_not_found_reason: true
  display_exceptions: true
  doctype: HTML5
  not_found_template: error/404
  exception_template: error/index
  template_map:
    layout/layout: /home/diego/Downloads/ZendSkeletonApplicationYaml/module/Application/view/layout/layout.phtml
    application/index/index: /home/diego/Downloads/ZendSkeletonApplicationYaml/module/Application/view/application/index/index.phtml
  template_path_stack:
  - /home/diego/Downloads/ZendSkeletonApplicationYaml/module/Application/view
strategies:
- ViewJsonStrategy
