service_manager:
  factories:
    translator: Zend\I18n\Translator\TranslatorServiceFactory
translator:
  locale: pt_BR
  translation_file_patterns:
        - type: gettext
          base_dir:  /../language
          pattern: '%s.mo'
controllers:
  invokables:
    Application\Controller\Index: Application\Controller\IndexController
view_manager:
  display_not_found_reason: true
  display_exceptions: true
  doctype: HTML5
  not_found_template: error/404
  exception_template: error/index
