modules:
  - Assets
  - Application
  - SpiffyRoutes
  - ZfcTwig
  - DoctrineModule
  - DoctrineMongoODMModule
module_listener_options:
  config_glob_paths:
    - config/autoload/{,*.}{global,local}.yml
  module_paths:
    - ./module
    - ./vendor
