#Configuração de carregamento para ambiente de desenvolvimento
modules:
  - DoctrineModule
  - DoctrineORMModule
  - DoctrineDataFixtureModule
  - ZendDeveloperTools
module_listener_options:
  config_glob_paths:
    - config/dev/autoload/{,*.}{global,local}.yml
