#Configuração do banco de dados de desenvolvimento
doctrine:
  connection:
    orm_default:
      driverClass: Doctrine\DBAL\Driver\PDOMySql\Driver
      params:
        host: "localhost"
        port: "3306"
        user: "root"
        password: "12345"
        dbname: "yaml"
        driverOptions:
          PDO::MYSQL_ATTR_INIT_COMMAND: "SET NAMES 'UTF8'"

doctrinetools:
  migrations:
      directory: data/migracoes
      namespace: Application\Migrations
      table: 'categorias'