zenddevelopertools:
  profiler:
    enabled: "true"
    strict: "false"
    flush_early: "false"
    cache_dir: "data/cache"
    matcher:
    collectors:
      db: false

  toolbar:
    enabled: true
    auto_hide: false
    position: bottom
    version_check: true
    entries:
      doctrine-odm: zend-developer-tools/toolbar/doctrine-odm