service_manager:
  factories:
    translator: Zend\I18n\Translator\TranslatorServiceFactory
translator:
  locale: pt_BR
  translation_file_patterns:
          - type: gettext
            base_dir: module/Assets/language
            pattern: '%s.mo'
view_manager:
  display_not_found_reason: true
  display_exceptions: true
  doctype: HTML5
  not_found_template: error/404
  exception_template: error/index
  template_map:
      layout/layout: module/Assets/view/layout/layout.phtml
      application/index/index: module/Assets/view/application/index/index.phtml
      error/404: module/Assets/view/error/404.phtml
      error/index: module/Assets/view/error/index.phtml
  template_path_stack:
      - module/Assets/view
assetic_configuration:
  debug: true
  buildOnRequest: true
  combine: true
  cacheEnabled: false
  cachePath: data/cache/assets
  default:
    assets:
    - '@base_css'
    - '@base_js'
    options:
      mixin: true
  webPath: public/assets
  basePath: assets
  modules:
    Assets:
      root_path: module/Assets/assets
      collections:
        base_css:
          assets:
          - css/style.css
          - ../../../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
          - ../../../vendor/twbs/bootstrap/dist/css/bootstrap-theme.min.css
          - ../../../vendor/fortawesome/font-awesome/css/font-awesome.min.css
          - ../../../vendor/components/jqueryui/themes/base/minified/*.css
          - ../../../vendor/components/jqueryui/themes/cupertino/jquery-ui.min.css
          - ../../../vendor/components/jqueryui/themes/cupertino/jquery.ui.theme.css
          filters:
            CssRewriteFilter:
              name: Assetic\Filter\CssRewriteFilter
        base_js:
          assets:
          - js/html5shiv.js
          - js/respond.min.js
          - js/jquery-1.10.2.min.map
          - ../../../vendor/malsup/form/jquery.form.js
          - ../../../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
          - ../../../vendor/components/jquery/jquery.min.js
          - ../../../vendor/components/jqueryui/ui/minified/jquery-ui.min.js
          - ../../../vendor/components/jqueryui/ui/minified/i18n/jquery.ui.datepicker-pt-BR.min.js
          - ../../../vendor/components/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
          filters:
            ?JSMinFilter:
              name: Assetic\Filter\JSMinFilter
        base_images:
          assets:
          - img/*.png
          - img/*.ico
          options:
            move_raw: true