doctrine:
  connection:
    orm_default:
      driverClass: Doctrine\DBAL\Driver\PDOMySql\Driver
      params:
        host: "localhost"
        port: "3306"
        user: "root"
        password: "anna"
        dbname: "yaml"
        driverOptions:
          PDO::MYSQL_ATTR_INIT_COMMAND: SET NAMES 'UTF8'
driver:
    Application_driver:
      class: Doctrine\ORM\Mapping\Driver\AnnotationDriver
      cache: array
      paths:
      - ./module/Application/src/Application/Entity
    orm_default:
      drivers:
        Application\Entity: Application_driver
data-fixture:
  Application_fixture: ./module/Application/src/Application/Fixture

