doctrine:
  connection:
    orm_default:
      driverClass: Doctrine\DBAL\Driver\PDOMySql\Driver
      params:
        host: seu host
        port: 3306
        user: seu usuario
        password: sua senha
        dbname: seu banco
        driverOptions:
          PDO::MYSQL_ATTR_INIT_COMMAND: SET NAMES 'UTF8'

