doctrine:
  connection:
    orm_defaul:
      driverClass: Doctrine\DBAL\Driver\PDOMySql\Driver
      params:
        host: 127.0.0.1
        port: 3306
        user: root
        password: 12345
        dbname: yaml