doctrine:
  connection:
    odm_default:
      server: localhost
      port: "27017"
      dbname: skeleton
      options: []
  configuration:
    odm_default:
      metadata_cache: array
      driver: odm_default
      generate_proxies: true
      proxy_dir: data/DoctrineMongoODMModule/Proxy
      proxy_namespace: DoctrineMongoODMModule\Proxy
      generate_hydrators: true
      hydrator_dir: data/DoctrineMongoODMModule/Hydrator
      hydrator_namespace: DoctrineMongoODMModule\Hydrator
      default_db: skeleton
      filters: []
  driver:
    odm_default:
      drivers:
        Application\Document: DTuX
    DTuX:
      class: Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver
      #cache: array
      paths:
      - module/Application/src/Application/Document
  documentmanager:
    odm_default:
      connection: odm_default
      configuration: odm_default
      eventmanager: odm_default
  eventmanager:
    odm_default:
      subscribers: []
  mongo_logger_collector:
    odm_default: []
  authentication:
    odm_default:
      objectManager: doctrine.documentmanager.odm_default
      identityClass: Application\Model\User
      identityProperty: username
      credentialProperty: password
service_manager:
  aliases:
    Doctrine\ODM\MongoDB\DocumentManager: doctrine.documentmanager.odm_default